### ISSUE TITLE
Can't get this plugin to work on fedora (same setup runs find with firewalld)

### ISSUE THREAD

**Issue by louisgtwo** [greenpau/cni-plugins#9]
$ ls -lZ /usr/local/lib/cni/
total 7340
-rwxr-xr-x. 1 root root system_u:object_r:var_t:s0 3750908 Apr 17 13:47 cni-nftables-firewall
-rwxr-xr-x. 1 root root system_u:object_r:var_t:s0 3761781 Apr 17 13:41 cni-nftables-portmap

$ sudo podman inspect podman
[
    {
        "cniVersion": "0.4.0",
        "name": "podman",
        "plugins": [
            {
                "bridge": "cni-podman0",
                "ipMasq": false,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.88.0.1",
                                "subnet": "10.88.0.0/16"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "cni-nftables-portmap"
            },
            {
                "forward_chain_name": "forward",
                "type": "cni-nftables-firewall"
            },
            {
                "type": "tuning"
            }
        ]
    }
]

Running rootless container:
$ podman run --pull=always --name "speedtest" --rm -p 8081:8080/tcp docker.io/openspeedtest/latest

$ sudo nft list ruleset
table ip filter {
	chain INPUT {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		iif "eno2" ip protocol icmp ct state { established, new } accept
		iif "eno2" ip saddr 172.16.2.0/24 tcp dport 22 ct state { established, new } accept
		iif "eno2" ip saddr 172.16.2.0/24 tcp dport 8081 ct state { established, new } accept
	}

	chain FORWARD {
		type filter hook forward priority filter; policy drop;
	}

	chain OUTPUT {
		type filter hook output priority filter; policy accept;
	}
}

**Comment by greenpau** [comment]
@louisgtwo , do you have firewalld running?

**Comment by greenpau** [comment]
dead letter.
